"""Add quiz_item.saved_at

Revision ID: 0673801da87d
Revises: b73f84074979
Create Date: 2022-08-06 13:55:42.104283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0673801da87d'
down_revision = 'b73f84074979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_item', sa.Column('saved_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_quiz_item_saved_at'), 'quiz_item', ['saved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_item_saved_at'), table_name='quiz_item')
    op.drop_column('quiz_item', 'saved_at')
    # ### end Alembic commands ###
